### ISSUE TITLE
laufend WARN mit 1.6.2

### ISSUE THREAD

**Issue by Negalein** [Grizzelbee/ioBroker.wireguard#106]
mit 1.6.2 kommen haufenweise dieser Meldungen.

Node.js: v18.19.0
NPM: 10.2.3
Admin: 6.15.2
JS-Controller: 5.0.17

```
2024-03-26 18:14:22.366  - [33mwarn[39m: wireguard.0 (1754650) Setting Nega-wg0.peers.PBQtaueqfB/GxwU6AElLQWXiRRlIPtBofbK1By9oBFY=.connected to false is senseless. Please open an issue on github and provide a debug log sowing the occurrence of this issue.
2024-03-26 18:14:22.366  - [33mwarn[39m: wireguard.0 (1754650) Setting Nega-wg0.users to null is senseless. Please open an issue on github and provide a debug log sowing the occurrence of this issue.
```

**Comment by m-s-b** [comment]
Node.js: v18.19.1
NPM: 10.2.4
Admin: 6.15.2
JS-Controller: 5.0.19

Hier ebenfalls:
`<html>
<body>

wireguard.0 | 2024-03-26 20:11:00.785 | warn | Setting Fontane-wg0.connectedUsersCount to 0 is senseless. Please open an issue on github and provide a debug log sowing the occurrence of this issue.
-- | -- | -- | --
wireguard.0 | 2024-03-26 20:11:00.785 | warn | Setting Fontane-wg0.connectedUsers to is senseless. Please open an issue on github and provide a debug log sowing the occurrence of this issue.
wireguard.0 | 2024-03-26 20:11:00.785 | warn | Setting Fontane-wg0.connectedPeersCount to 0 is senseless. Please open an issue on github and provide a debug log sowing the occurrence of this issue.
wireguard.0 | 2024-03-26 20:11:00.785 | warn | Setting Fontane-wg0.connectedPeers to is senseless. Please open an issue on github and provide a debug log sowing the occurrence of this issue.


</body>
</html>`
Nach Downgrade auf 1.6.1 wieder alle chic.

**Comment by Grizzelbee** [comment]
sollte mit der 1.6.3 erledigt sein.

**Comment by m-s-b** [comment]
@Grizzelbee 
Danke, Warnmeldungen sind bei mir mit der 1.6.3 weg

**Comment by Negalein** [comment]
@Grizzelbee 
Danke, läuft wieder :)
