### ISSUE TITLE
Adapterlogo als png anstatt svg einbinden

### ISSUE THREAD

**Issue by ipod86** [Grizzelbee/ioBroker.wireguard#26]
Hallo,

ist es möglich unter iobroker/iobroker-data/files/wireguard.admin das Logo als png (oder zusätzlich) anstatt svg einzubinden?

Ich habe über 60 Adapter am laufen und nur dieser hat ein svg.

Ist an sich ja ziemlich egal ^^, jedoch habe ich für meine vis einen Tabelle meiner Adapter die auf das Bild zurück greift.
Leider ist es was schwierig per Skript die Endung des Bildes auszulesen.

**Comment by Grizzelbee** [comment]
Hallo @ipod86 

hmm. Ehrlich gesagt würde ich das ungern machen - ich habe svg ja durchaus bewusst als Format für die Grafik verwendet.
Aber wenn du da eh per script drangehst, gibt es vielleicht doch eine Lösung:
Ich weiß ja nicht, wie du über an deine Adapterlistze kommst, aber wenn du eh in die jeweiligen Verzeichnisse reingreifst, kannst du auch die io-package.json einlesen. Das ist ein simples json-objekt und in `icon` und  `extIcon` steht der Name des Icons für jeden Adapter drin. Das ist ein Pflichtfeld bei jedem Adapter.
![grafik](https://user-images.githubusercontent.com/5459426/168670330-835945f3-2cd6-4ff1-80a5-f916e66fc17a.png)

Versuch doch das als erstes - und wenn das nicht funktioniert, können wir gerne noch einmal reden. Aber ich bin mir relativ sicher, das das nicht der einzige Adapter bleibt, der keine png verwendet.

**Comment by ipod86** [comment]
Danke, das kann ich mal versuchen.
Mal schauen, ob ich aus Blockly eine möglichkeit finde auf die json Datei zuzugreifen.

Im Moment suche ich mit "id von Selektor" den alive Status. Aus dem Pfad Bastel ich dann den link zum Bild zusammen.

![Screenshot_20220516-222221_Chrome](https://user-images.githubusercontent.com/66136363/168676119-973c517c-d146-47a9-a9d2-d4b3ac72c7fc.jpg)

**Comment by Grizzelbee** [comment]
> Danke für den Tipp. Hab es mit Pauls Hilfe hinbekommen.

Das freut mich! :)
Und der weitere Vorteil ist, dass du jetzt eine wirklich saubere Lösung hast, die garantiert immer funktioniert - es sei denn der Adapterentwickler vebastelt das selbst. ;)
