### ISSUE TITLE
SSH alternative port support

### ISSUE THREAD

**Issue by Osrx** [Grizzelbee/ioBroker.wireguard#37]
Is there any chance to add an alternative SSH port for host IP address?
For example 192.168.1.2:22222 where 22222 is SSH port.

Also on my server I have multiple containers with Wireguard with different names (wireguard and wireguard1), and I have no way to check them with this probe... =(

Thank you!

**Comment by Grizzelbee** [comment]
To be honest: 
The only reason why these options are missing is the admin GUI. I'm just missing space for these options.

I need to rethink the GUI. 

I currently think to add an overlay dialog that grabs all the needed config options. 
But I'm not deeply into REACT and don't know how to do that.
So I need to figure it out.
