### ISSUE TITLE
Bug: Objekte werden ständig geändert

### ISSUE THREAD

**Issue by Scrounger** [Grizzelbee/ioBroker.wireguard#61]
Hab heute gesehen das meine redis object datei enorm groß war. Bei näherer Untersuchung habe ich festgestellt, dass der wireguard adapter pro minute ca. 10 mal die Objekte unter `wireguard.0.lxc_WireGuard-wg0.peers.*` ändert / neu erzeugt.

Denke es liegt hier dran:
https://github.com/Grizzelbee/ioBroker.wireguard/blob/3309743b99814c9e11a08d044247a613359f3cef/main.js#L273

Die If Bedinung müsste doch so aussehen `if ( objData.common.name === oldObj.common.name )` oder ?

`name` gibt es meines wissen nach nur im `common` objekt

**Comment by Grizzelbee** [comment]
Du hast vollkomment recht. 
Das muss natürlich `if ( objData.common.name === oldObj.common.name )` heißen.
Ich fixe das kurzfristig.
