### ISSUE TITLE
Please correct npm maintainers configuration.

### ISSUE THREAD

**Issue by GermanBluefox** [Grizzelbee/ioBroker.wireguard#62]
## ioBroker adapter checker for npm access

Access right check for adapter wireguard returned the following issue:

Bluefox was not found in the collaborators on NPM!.
Please execute in adapter directory: "npm owner add bluefox iobroker.wireguard"

Current maintainers are 
    apollon77 <github@fischer-ka.de>
    grizzelbee <hanjo@hingsen.de>

Please fix the above error as soon as possible.
All adapters listed at ioBroker repositories must have 'bluefox' added as maintainer.

Future version updates at the repositories will be suspended until this problem is fixed.

**Comment by mcm1957** [comment]
Please add bluefox to npm

**Comment by Grizzelbee** [comment]
\WebstormProjects\ioBroker.wireguard> npm owner ls iobroker.wireguard  
bluefox <dogafox@gmail.com>
apollon77 <github@fischer-ka.de>
grizzelbee <hanjo@hingsen.de>

**Comment by mcm1957** [comment]
Thanks
